version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        ports:
        - "8000:80"
        depends_on:
        - db
        entrypoint: /bin/bash -c "cp .env.example .env && php artisan key:generate && php artisan migrate && apache2-foreground"
    db:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
                MYSQL_ROOT_PASSWORD: rootpass
                MYSQL_DATABASE: db
                MYSQL_USER: user
                MYSQL_PASSWORD: supersecret
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    nginx:
        image: nginx:stable-alpine
        volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
        - "8080:80"  # Change this line to map a different host port
        - "443:443"
        depends_on:
        - app
        - db

volumes:
  mysql-volume:
