services:
  app:
    scale: 2
    build:
      context: .
      dockerfile: Dockerfile
    image: mostafaramdan5544/laravel-docker
    depends_on:
      - db
      - phpmyadmin
    entrypoint: /bin/bash -c "cp .env.example .env && php artisan key:generate && php artisan migrate && apache2-foreground"
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "9001:80"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - db
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_POLL_INTERVAL=30
    command: --cleanup --interval 30 laravel-docker-app-1 laravel-docker-app-app-2
volumes:
  mysql-volume:
